apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $GCLOUD_APP
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: $GCLOUD_APP
    spec:
      containers:
        - name: $GCLOUD_APP
          image: gcr.io/$GCLOUD_PROJECT/$GCLOUD_APP
          ports:
            - containerPort: 4369
            - containerPort: 10000
            - containerPort: 10001
            - containerPort: 10002
            - containerPort: 10003
            - containerPort: 10004
            - containerPort: 10005
          env:
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
