apiVersion: v1
kind: Service
metadata:
  name: disterltest
  labels:
    app: disterltest
spec:
  clusterIP: None
  ports:
    - port: 10000
      targetPort: 10000
      name: disterl-mesh-0
    - port: 4369
      targetPort: 4369
      name: epmd
  selector:
    app: disterltest
  type: ClusterIP
